### ISSUE TITLE
Add logic for Thinkful Dev vs Design grading

### ISSUE THREAD

**Issue by nikibrown** [nikibrown/bloc-grading-chrome-extension#4]
Hi @obedparla Since you updated the chrome extension to work for both platforms I'd like you to add a bit more logic for graders to conditionally include a design or dev grading signature. 

I've added grading signature text for Bloc grading, Thinkful Dev grading, and Thinkful Design grading in our best practices document: https://docs.google.com/document/d/1SE0H9J60Q-SjsbW8oE_dSQ1Jkhwh0aem5u7wR23RwvE/edit#heading=h.tq9dfm7u553d 

What I'm envisioning (not sure the best way to do this) is to just have a variable that the grader sets to true or false for dev grading (or design grading). Whatever is easiest - since everyone needs to go in and edit and enter their name. 

Would love you know your thoughts?  Thanks so much for your help with this!

Please bill this as grading time and leave a comment that this is for the chrome extension.

**Comment by obedparla** [comment]
Hey Nikki, great idea, will work on this right away.

**Comment by nikibrown** [comment]
Awesome! Thanks Obed!
